import Link from "next/link";

export const metadata = {
  title: "Ristorante nome",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <div className="flex items-center justify-center min-h-screen text-3xl">
      <Link href={'/menu'}>Vai al menù</Link>
    </div>
  );
}
